apiVersion: v1
kind: Pod
metadata:
  name: busybox-stable
spec:
  containers:
    - name: busybox
      image: busybox:1.36
      command:
        - /bin/sh
        - -c
        - |
          sleep 5
          echo "Starting application successfully..."
          tail -f /dev/null