apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 405804179058.dkr.ecr.ap-south-1.amazonaws.com/order-service:v1
          ports:
            - containerPort: 5001
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: ordersdb
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: password
            - name: DB_PORT
              value: "5432"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "256Mi"
              cpu: "500m"

          readinessProbe:
            httpGet:
              path: /health
              port: 5001

            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
