name: Build and Push to ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: "405804179058"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::405804179058:role/GitHubActions-EKS-Deploy
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push user-service
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -t $REGISTRY/user-service:$IMAGE_TAG \
            ./user-service

          docker push \
            $REGISTRY/user-service:$IMAGE_TAG

      - name: Build and push order-service
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -t $REGISTRY/order-service:$IMAGE_TAG \
            ./order-service

          docker push \
            $REGISTRY/order-service:$IMAGE_TAG
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name devops-microservice-cluster

      - name: Test EKS access
        run: |
          kubectl get nodes
          kubectl get pods -A
      - name: Deploy PostgreSQL
        run: |
          kubectl apply -f k8s/postgres-pvc.yaml
          kubectl apply -f k8s/postgres-service.yaml
          kubectl apply -f k8s/postgres.yaml

      - name: Deploy application services
        run: |
          kubectl apply -f k8s/user-service-svc.yaml
          kubectl apply -f k8s/order-service-svc.yaml
          kubectl apply -f k8s/user-service.yaml
          kubectl apply -f k8s/order-service.yaml

      - name: Update user-service image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          kubectl set image deployment/user-service \
            user-service=$REGISTRY/user-service:$IMAGE_TAG

      - name: Update order-service image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          kubectl set image deployment/order-service \
            order-service=$REGISTRY/order-service:$IMAGE_TAG

      - name: Wait for user-service rollout
        run: |
          kubectl rollout status deployment/user-service --timeout=180s

      - name: Wait for order-service rollout
        run: |
          kubectl rollout status deployment/order-service --timeout=180s

      - name: Verify deployment
        run: |
          echo "===== DEPLOYMENTS ====="
          kubectl get deployments

          echo "===== PODS ====="
          kubectl get pods -o wide

          echo "===== SERVICES ====="
          kubectl get svc
